In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame()

In [3]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [4]:
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df1)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [5]:
df1.head(2)

0  1  2
0  1  2  3
1  4  5  6

In [6]:
df1.tail(2)

0  1  2
1  4  5  6
2  7  8  9

In [7]:
df1.shape

(3, 3)

In [8]:
df1.iloc[0,1]

2

In [10]:
df1.iloc[0:2,0:2]

0  1
0  1  2
1  4  5

In [5]:
import pandas as pd
import numpy as np
# Pandas DataFrame
df = pd.DataFrame(data={'A': [3, 2, 1], 'B': [6,5,4], 'C': [9, 8, 7]}, 
                  index=['i', 'j', 'k'])
print("Pandas DataFrame: ")
print(df)


Pandas DataFrame: 
   A  B  C
i  3  6  9
j  2  5  8
k  1  4  7


In [3]:
# Convert Pandas DataFrame to NumPy Array
np_arr = df.to_numpy()
print("Pandas DataFrame to NumPy array: ")
print(np_arr)

Pandas DataFrame to NumPy array: 
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [6]:
# Convert specific columns of Pandas DataFrame to NumPy array
arr = df[['B', 'C']].to_numpy()
print("Convert B and C columns of Pandas DataFrame to NumPy Array: ")
print (arr)

Convert B and C columns of Pandas DataFrame to NumPy Array: 
[[6 9]
 [5 8]
 [4 7]]
